### ISSUE TITLE
Zone off status can’t be set

### ISSUE THREAD

**Issue by Grumpy4711** [athombv/com.tado#1]
~~This is my first issue that i report in GitHub, so maybe this is not correct reported.~~

~~Radiator thermostat shows up as wall thermostat.~~

I am a homey user for a week now and the tado integration was a priority for me.
Almost everything is working only the zone off status can’t be set en when it’s set by tado you can’t see it.

**Comment by OpenMindNL** [comment]
The device icon shows a combination of the Smart Thermostat and Smart Radiator Thermostat for all heating zones.

So... It doesn't matter what heating devices you use, the icon and capabilities will always be the same.
"Hot Water" control will show the same icon but less capabilities.

**Comment by Grumpy4711** [comment]
Alex,

The icon is not a big problem.
I am a homey user for a week now and the tado integration was a priority for me.
Almost everything is working only the zone off status can’t be set en when it’s set by tado you can’t see it.



Met vriendelijke groet,

Joop Perlee

Van: Alex
Verzonden: maandag 4 december 2017 23:49
Aan: athombv/com.tado
CC: Grumpy4711; Author
Onderwerp: Re: [athombv/com.tado] Radiator thermostat shows up as WallThermostat (#1)

The device icon shows a combination of the Smart Thermostat and Smart Radiator Thermostat for all heating zones.
So... It doesn't matter what heating devices you use, the icon and capabilities will always be the same.
"Hot Water" control will show the same icon but less capabilities.

**Comment by Grumpy4711** [comment]
Hi Alex,

I have now installed the beta 1.1.1, this looks very good.
Can i send testing results to this mail address or do i send it a GitHub.


Met vriendelijke groet,

Joop Perlee

Van: Alex
Verzonden: maandag 4 december 2017 23:49
Aan: athombv/com.tado
CC: Grumpy4711; Author
Onderwerp: Re: [athombv/com.tado] Radiator thermostat shows up as WallThermostat (#1)

The device icon shows a combination of the Smart Thermostat and Smart Radiator Thermostat for all heating zones.
So... It doesn't matter what heating devices you use, the icon and capabilities will always be the same.
"Hot Water" control will show the same icon but less capabilities.

**Comment by OpenMindNL** [comment]
Better keep posting on GitHub, so other users can see when an issue is already known.

**Comment by OpenMindNL** [comment]
Sorry... missed your remark about Zone Off.

I have been thinking about that, but the problem at this moment is that the space on the mobile card is to small to add an additional button. It would take away a lot of space from the scrolling 'Sensor bar'.
The new mobile app that Athom is building right now, will offer enough space for additional options so we might implement an Off-button by that time.

For now it is possible to set a zone to OFF by using a flow with the corresponding Action flow card.

To display the status, I have choosen to set the thermostats in the mobile card to their minimal setting whenever a zone is set to OFF. That is 30 degrees Celcius for Hot Water and 5 degrees for any Heating device, which is the same setting that tado uses for 'frost protection'.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2615
