### ISSUE TITLE
Presence Detection Faulty since 1.2.1

### ISSUE THREAD

**Issue by bogga666** [athombv/com.tado#11]
I have had the same problems as others when the Tado app updated automatically. A uninstall seemed to resolve the problem with the app crashing after a 5 minutes or so. 

However, since then the presence detection now says that "everyone is out", regardless of the Tado's actual status.

**Comment by StraDijk** [comment]
True, same issue here.

**Comment by WeeJeWel** [comment]
Fixed in v2.0.0. Re-pair your devices.
