### ISSUE TITLE
Devices unauthorized with +7 zones and version 2.0.1

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [athombv/com.tado#15]
With version 2.0.1 and my 7 zones with multiple devices I get the problem that they are automatically unauthorized.

After first installation of v2.0.1 I had immediate memory problems (multiple mem.max reached 125MB) , devices unauthorized and only by removing Tado app, reboot and install Tado app again it started to work.

First I only added 2 devices (Home and Water) , and for 2 days that worked fine. Memory usage in developer app profiling was around 24MB.
Then I added the other 5 zones (total of 10 devices and 7 zones). Memory shoot to 95MB and CPU was around 13%-14%.

Within a day all devices are unauthorized again.

The Home device is used in flow cards to detect presence and used to enable smart schedules or switch off with outside temperature.

**Comment by AdyRock** [comment]
I also have some devices that now say they have been unauthorised, one rad valve and the Home / Away. I have tried deleting them and adding them back but they say unauthorised straight away.
All worked well up until the updated to 2.0.1.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2612
