### ISSUE TITLE
Unable to run from developer console

### ISSUE THREAD

**Issue by AdyRock** [athombv/com.tado#16]
I am experiencing the issue with devices becoming unauthorized on a regular basis since the 2.0.1 update so I have grabbed a zip of the project and unpacked it on my PC. Then I used the Athom developer console to run the app. I was hoping to fix the problem but the app immediately fails reporting it can't find the CLIENT_ID.
I have added an env.json file and added the CLIENT_ID and CLIENT_SECRET entries so the app will run. Then I add the tado device and I get the tado login window. I enter my tado username and password but it then shows an error page saying something like "that shouldn't of happened, the client credentials are invalid". I know for sure I entered the correct user name and password so any idea what I am missing?

**Comment by StraDijk** [comment]
Got the same issue. All devices become unauthorized after adding them.

**Comment by WeeJeWel** [comment]
Fixed in v3.0
