### ISSUE TITLE
Tado Loses its connection 

### ISSUE THREAD

**Issue by philsniff** [athombv/com.tado#17]
After one to two days the tado devices are broken under devices in homey. (Chain Symbols) Deleting and readding will only work for another little Periode. 
So heatingautomation is not possible with the tado app at the Moment. But it is getting important now.

**Comment by 2benl** [comment]
Same here, See https://community.athom.com/t/unauthorized-tado-thermostat-and-thermostatic/2079/17

**Comment by jeroenspruijt** [comment]
Same here for a long time now, and is a don't always use the Desktop APP it's hard to see it in the Mobile APP as they don't show up as a failed device

Any news or work around ?

**Comment by Shadowz7** [comment]
Same here for a long time now.
Any news or work around ?

**Comment by WeeJeWel** [comment]
I'll be focusing on this problem a.s.a.p.

**Comment by 2benl** [comment]
Will be greatly appreciated.

**Comment by WeeJeWel** [comment]
Fixed in v3.0.0. It's published as alpha at https://apps.athom.com/app/com.tado. If you'd like to test, send me your Athom account's e-mail address and I'll add you as a tester.

**Comment by Shadowz7** [comment]
Shadowz7@gmx.de

Gesendet von Mail für Windows 10

Von: Emile Nijssen
Gesendet: Freitag, 14. Dezember 2018 14:41
An: athombv/com.tado
Cc: Shadowz7; Comment
Betreff: Re: [athombv/com.tado] Tado Loses its connection (#17)

Fixed in v3.0.0. It's published as alpha at https://apps.athom.com/app/com.tado. If you'd like to test, send me your Athom account's e-mail address and I'll add you as a tester.

**Comment by jeroenspruijt** [comment]
Wil graag mee doen in alpha test tado v3

Jeroenspruijt@upcmail.nl

Met vriendelijke groet,

Jeroen Spruijt

**Comment by WeeJeWel** [comment]
@korkmazk v3.0.0 staat ondertussen als stable in de Homey App Store

**Comment by korkmazk** [comment]
> @korkmazk v3.0.0 staat ondertussen als stable in de Homey App Store

Ah ik zie al dat ik hem al heb. We gaan weer eens opnieuw autoriseren.
thx!
