### ISSUE TITLE
JavaScript no_mobil

### ISSUE THREAD

**Issue by philsniff** [athombv/com.tado#19]
i just installed the 3.0 version of the tado-app. everything looks good except the home status of my mobil (iphone 8) . i deletes the thermostates in homy and readded them, but: “no_mobil” is displayed at the devicecard. It is a JavaScript when klickend the wrench. See forum with Screenshot: https://community.athom.com/t/unauthorized-tado-thermostat-and-thermostatic/2079/61?u=phils

Homey Firmware 1.5.13

**Comment by MP-ICT-Diensten** [comment]
I have had some kind of crash with my Homey, and I have now the same error with the Home (Woning): no_mobile  if  I look to the device.
I removed tado app (version 3.0.2), reboot of Homey and installed App againg, but same result.

Also still using version 1.5.13 in Homey.

**Comment by regnerus** [comment]
Closing this issue since it is only relevant to an older version of the Homey Tado app.
