### ISSUE TITLE
Toggle tado's home/away status from action card

### ISSUE THREAD

**Issue by kaohlive** [athombv/com.tado#20]
I use my tado with smart schema's based around geofencing. Now the tado's geofencing in the mobile app sometimes falls over. I also use smarter home/away detection for my homey users using different triggers. I would love to be able to use the homey presence status and push it to my tado. 
In the mobile devices endpoint (https://my.tado.com/api/v2/homes/<homeID>/mobileDevices old api doc) there is data per device if they are @home or not. I would love an action card to be able to set that info;
If homey user X comes home set tado user X to at home
It would improve my control greatly specially for users that are not part of my home heating apps nor homey apps but that I track by wifi for example (the babysitter for example).

**Comment by regnerus** [comment]
@kaohlive unfortunately it is not possible to set the home/away status of the Tado app directly from Homey due to an API limitation. Instead it is possible to use Homey's presence detection to turn your smart schema on and off which will give you the same result.
