### ISSUE TITLE
Clima Control V3+

### ISSUE THREAD

**Issue by ad1240de** [athombv/com.tado#28]
Will be possible to control = switch on and off a Clima (AC) unit (same as in TADO app for android) ?

Kr
Andreas

**Comment by regnerus** [comment]
Hi @ad1240de, thanks for your request however since this issue is not directly related to the Tado app I am closing it here. 

If you want to request a Homey app please follow this post on our Community Forum: https://community.athom.com/t/homey-community-app-requests/2713
