### ISSUE TITLE
Two tags with the same name in Beta 1.1.1

### ISSUE THREAD

**Issue by Grumpy4711** [athombv/com.tado#4]
There are two tags with the same name in Flows "Smart schedule"
It's double function the first one is Manual and the second is Smart schedule.
When Manual is true Smart schedule is false and visa versa.
It's only confusing building a flow.

**Comment by OpenMindNL** [comment]
Yup... "Manual" should not be there at all.
It was a wrong implementation in v1.0.0 and should be replaced by "Smart schedule" in v1.1.0

However, there's some left-over in the code that causes an additional "Smart schedule" tag to appear, just like additional "Insights data". Their functionality is exactly opposite from each other. The one that shows like "ON" when smart schedule is off (so it shows Manual Mode), should be ignored for now.... and should be removed in a future version.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2614
