### ISSUE TITLE
Error invalid_grant

### ISSUE THREAD

**Issue by iOurea** [athombv/com.tado#9]
After the update to beta 1.2.1 I get the following:
![image](https://user-images.githubusercontent.com/23391397/35623359-9a59ccb4-068b-11e8-81bf-2835aabdc9e7.png)

when I hoover with the mouse on the icon the message invalid_grant is visible.

**Comment by WeeJeWel** [comment]
Does this also happen after an app restart?

**Comment by iOurea** [comment]
Yes, tried several times

Met vriendelijke groet,
Johan-Peter

Van: Emile Nijssen<mailto:notifications@github.com>
Verzonden: donderdag 1 februari 2018 10:59
Aan: athombv/com.tado<mailto:com.tado@noreply.github.com>
CC: Johan-Peter Couprie<mailto:johanpeter@couprieconsultancy.eu>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [athombv/com.tado] Error invalid_grant (#9)


Does this also happen after an app restart?

**Comment by WeeJeWel** [comment]
Did you previously authenticate with a username & password, or with a popup?

**Comment by iOurea** [comment]
The previous i authenticate with a popup where I put in my username /password.

Met vriendelijke groet,
Johan-Peter

Van: Emile Nijssen<mailto:notifications@github.com>
Verzonden: donderdag 1 februari 2018 11:11
Aan: athombv/com.tado<mailto:com.tado@noreply.github.com>
CC: Johan-Peter Couprie<mailto:johanpeter@couprieconsultancy.eu>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [athombv/com.tado] Error invalid_grant (#9)


Did you previously authenticate with a username & password, or with a popup?

**Comment by StraDijk** [comment]
Same here.. Have to authenticate every 2 days or so.

**Comment by StraDijk** [comment]
App unusable at this point it keeps disconnecting since yesterday.

**Comment by WeeJeWel** [comment]
How many devices do you have connected?

**Comment by iOurea** [comment]
I have 11 groups with 12 devices.
After I have installing RC11 I have removed all deviced and deinstalled the Tado app.
Then I have installed the Tado app again and connected the devices.

Since then everyting is working correctly.

**Comment by StraDijk** [comment]
- Installed RC 11 
- uninstalled tado app
- reboot
- installed tado apps
- Re-added the devices (could only at 1 device at the time and had to enter credentials each time)

It seems to be working again.

**Comment by iOurea** [comment]
Issue is solved
